-- insert into new_table (login, password) values('Bob','Bob');
-- #select login,password from new_table where id=1;
-- #update new_table set password='admin' where id=2;
-- #select * from new_table
-- delete from new_table
